### PR TITLE
Add support for "--build" on "hocker_run"

### PR DESCRIPTION
**Pull request by tianon**
This is a request for thoughts -- this allows for building images directly via Hocker (useful for dev boxes or small deployments where a registry or Docker Hub push are overkill).

Basically, the only time `docker build` would actually be invoked by this are the necessary image missing entirely or `--pull always` being specified.

### CODE REVIEW

**Comment by yosifkit** [comment]
It seems a little weird to piggyback the build on the value of `pull` and doesn't currently give a way to `docker build` without pull.   It is more complicated, but it might be better to have our `pull` flag affect whether we add `--pull` to the `docker build`.

- `--pull=always --build="$absDir"` -> `docker build --pull`
- `--pull=never --build="$absDir"` -> `docker build`
  - will have to check if `FROM` image exists to throw `script_error` on missing image
- `--pull=missing --build="$absDir"` -> `docker build`
- an option to not try rebuilding (maybe just not setting `--build`?)

**Comment by tianon** [comment]
If we do that, we'll definitely need to add a `--build` to the public UX -- "not specifying build" would imply that if a container's image requires a `docker build`, we run `docker build` every single time we want to test whether it should be re-launched. :disappointed:

**Comment by tianon** [comment]
Maybe we just bite the bullet and actually do `--build=always`, `--build=missing`, `--build=never`, and it's a noop if `--build` isn't specified on `hocker_run`?

**Comment by yosifkit** [comment]
Yes, to the no-op if you say `./myimage --build=always` and it doesn't have a build step, otherwise it will make multi-hocker break when some have builds and some don't.

**Comment by tianon** [comment]
Finally updated this with the logic as-discussed -- now `./hocker-script -pbs` will pull the base image, build the container image, then smart-restart based on whether build cache actually allowed the image to build. :+1:

**Comment by tianon** [comment]
```console
$ ./htop -pbs

Pulling 'alpine:3.5' ...
3.5: Pulling from library/alpine
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
Status: Image is up to date for alpine:3.5

Building 'htop' (from '/home/tianon/infosiftr/hocker/example/.htop') ...
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine:3.5
 ---> 4a415e366388
Step 2/3 : RUN apk add --no-cache htop
 ---> Running in b3fdaf7a19ef
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.5/community/x86_64/APKINDEX.tar.gz
(1/4) Installing ncurses-terminfo-base (6.0-r7)
(2/4) Installing ncurses-terminfo (6.0-r7)
(3/4) Installing ncurses-libs (6.0-r7)
(4/4) Installing htop (2.0.2-r0)
Executing busybox-1.25.1-r0.trigger
OK: 11 MiB in 15 packages
 ---> ac181423825e
Removing intermediate container b3fdaf7a19ef
Step 3/3 : CMD htop
 ---> Running in 4b5e8652a8f1
 ---> 1fb27b0051a6
Removing intermediate container 4b5e8652a8f1
Successfully built 1fb27b0051a6


Starting 'htop' (from 'htop') ...
a88ffc34a1946c75c868e97e419ffd6e690200ad3fc79317796c2dbbf09b5479

$ ./htop -pbs

Pulling 'alpine:3.5' ...
3.5: Pulling from library/alpine
Digest: sha256:58e1a1bb75db1b5a24a462dd5e2915277ea06438c3f105138f97eb53149673c4
Status: Image is up to date for alpine:3.5

Building 'htop' (from '/home/tianon/infosiftr/hocker/example/.htop') ...
Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM alpine:3.5
 ---> 4a415e366388
Step 2/3 : RUN apk add --no-cache htop
 ---> Using cache
 ---> ac181423825e
Step 3/3 : CMD htop
 ---> Using cache
 ---> 1fb27b0051a6
Successfully built 1fb27b0051a6

Not restarting 'htop' (--redeploy 'smart')

```

**Comment by tianon** [comment]
And to show one that isn't using `--build`:
```console
$ ./rawdns -pbs

Pulling 'tianon/rawdns' ...
Using default tag: latest
latest: Pulling from tianon/rawdns
Digest: sha256:417807b6c4bf14e3f8b48328f3df536e16e0f236a0580e6f21750c6b3d3cdbd8
Status: Image is up to date for tianon/rawdns:latest

Not restarting 'rawdns' (--redeploy 'smart')

```

**Review by yosifkit — APPROVED** [review]

**Pull request merged**
